### ISSUE TITLE
Update /benchmarks to load benchmarks instead of tasks [ENG]

### ISSUE THREAD

**Issue by tessathornberry** [sfbrigade/compass#198]
Currently, the /benchmarks tab loads all task instances, when it should perhaps load a list of benchmarks, and clicking on the benchmark should load the task instances, for assignment to staff or data collection

![Image](https://user-images.githubusercontent.com/105292208/268826738-b46b1d71-ee5b-41da-909d-ffbb8901a4f9.png)

**Comment by jonahchoi** [comment]
Seems like the issue is actually being able to press the 'assign' button multiple times. Each click adds a brand new task, resulting in the repeats seen here. I haven't been able to recreate it in other ways. Let me know if you see anything different. Since the UI hasn't been made for assigning benchmarks, I could add a quick change for the temporary function we have to prevent multiple assignments.
