### ISSUE TITLE
Create and Unit Test "Add Staff" email invitations [ENG]

### ISSUE THREAD

**Issue by tessathornberry** [sfbrigade/compass#213]
This ticket should be accomplished with teamwork from 2-4 engineers.

The goal is that when a Case Manager adds a staff member, that staff member receives an invitation to join the app. Part of this is set up with nodemailer and getTransporter in /backend/routers/para.ts, however, we need to implement it and test it.

Please see the comments in <a href="https://github.com/sfbrigade/compass/issues/29">issue # 29</a> to get started.

**Comment by BrettEastman** [comment]
FYI - What is described above was already completed for ticket #29 by Brett and Max back in June, including Ava testing. However, it is possible that mockery may be out of date. Otherwise, I have updated the email, based on Neha's template in ticket #103 and it is currently in review in a PR for #199 and #123
