### ISSUE TITLE
Speed up staff name rendering time after addition [ENG]

### ISSUE THREAD

**Issue by tessathornberry** [sfbrigade/compass#215]
This is unnecessary but could make a small improvement and could be a good first issue:

Currently it takes a moment for the staff name of a new staff member to populate the staff list. Much of this is because of the join tables we are using. 
Explore speeding this up, maybe with CREATE INDEX at the bottom of the the 1_initial-migrations.sql file.

Docs:
https://www.postgresql.org/docs/current/sql-createindex.html
https://www.postgresqltutorial.com/postgresql-indexes/postgresql-create-index/

**Comment by shin101** [comment]
Update : Create mutation seems to be the reason for the lag (see screenshot + recording). Since the lag is not from fetching data, create Index may not resolve this issue

![Screenshot 2023-10-23 at 7 00 50 PM](https://github.com/sfbrigade/compass/assets/44033225/ec470b6b-a399-4301-a48a-7367b7cce113)

https://github.com/sfbrigade/compass/assets/44033225/17267645-839e-4350-97cd-a9f0a7a8b111

**Comment by tessathornberry** [comment]
Great idea! Let's close this issue and since you have figured out the cause, come up with a solution that works to manage the user's expectations instead of the speed of the transaction!
