### ISSUE TITLE
Stepper component for Benchmark creation [ENG]

### ISSUE THREAD

**Issue by tessathornberry** [sfbrigade/compass#325]
Create reusable Stepper component based on the Figma file -> Design Systems

Use best judgment to standardize the Stepper component according to the Design Systems guidelines for primary, secondary, etc.

https://www.figma.com/design/m09znscRXNqSziAiEbNLTf/Compass-Designs?node-id=1-9&t=h8LMqclvnxY0lZ58-0

---

Additional details copied from #342:
> Implement in the Design Systems a "Stepper" component. [MaterialUI provides this](https://mui.com/material-ui/react-stepper/#customized-horizontal-stepper), though I'm not sure if one of these formats will match the design. If necessary, this can be extracted to a separate issue and replaced here with a placeholder.

**Comment by nickvisut** [comment]
hi @KCCPMG, please let me know if this should be directed elsewhere. I just have a couple of questions that you may be able to answer wrt the stepper:
- Will the "stepper" component ever have more than two steps? Should it be interactive (clickable)? If yes, can you describe the interaction?
- Can you speak to the different states shown in Figma? (there appear to be neutral or "in-progress" states)
- Will our flows be linear or non-linear (do the "steps" have to be done in order?)

**Comment by KCCPMG** [comment]
> hi @KCCPMG, please let me know if this should be directed elsewhere. I just have a couple of questions that you may be able to answer wrt the stepper:
> 
> * Will the "stepper" component ever have more than two steps? Should it be interactive (clickable)? If yes, can you describe the interaction?
> * Can you speak to the different states shown in Figma? (there appear to be neutral or "in-progress" states)
> * Will our flows be linear or non-linear (do the "steps" have to be done in order?)

I believe that the stepper component is actually also used (or something very similar) in the rendered benchmarks when looking at a goal (issue #341 ), so yes, I believe that it should be able to show progress. Having said that, I believe that the flow of these intake forms will basically be an all-or-nothing aspect of the stepper component. I couldn't actually see the design systems version of a stepper component in Figma, (I might not be looking in the right place), so the only version of the stepper component that I've seen has been the one used in the create-benchmark-flow. I'm not sure what you're asking wrt the flows being linear or non-linear, unless that's really a question for #342, in which case I believe that the form flow there should be linear. I'd like to answer any questions you have, but when they get to this level of design, the best way to eliminate ambiguity would likely be to talk to Neha in slack. If you do, please include me in the conversation so that I can be aware of any particulars in the issue that I've missed.

**Comment by nickvisut** [comment]
Thanks for the response, @KCCPMG. The stepper component is here: https://www.figma.com/design/m09znscRXNqSziAiEbNLTf/Compass-Designs?node-id=7371-22671&t=X99ksPhw6HNYvjL7-1.

Thanks for the lowdown on the benchmark flow. I'll ping Neha if I have additional questions.

**Comment by nickvisut** [comment]
Here is a usage of the stepper component on the new Add benchmark flow: https://www.figma.com/design/m09znscRXNqSziAiEbNLTf/Compass-Designs?node-id=13077-24486&t=53YWcWlMd9fE8JvY-4

**Comment by nickvisut** [comment]
View benchmark code for reference: https://github.com/sfbrigade/compass/pull/347
