### ISSUE TITLE
Add global error handler for trpc

### ISSUE THREAD

**Issue by codetheweb** [sfbrigade/compass#84]
There should be a global error handler passed as an option to the trpc provider in `src/pages/_app.tsx` that shows a toast or alert on API errors.

**Comment by shin101** [comment]
Before writing any code I wanted to do a sanity check and make sure my understanding is aligned with what this task is looking for...

I took at look at `src/pages/_app.tsx` as well as [react-toastify](https://fkhadra.github.io/react-toastify/positioning-toast) we could potentially use.

I could return something like <trpc.Provider client={trpcClient} queryClient={queryClient} **onError={handleError}**> and create a separate handleError function that shows toast error message

Did I understand this correctly?

**Comment by codetheweb** [comment]
MUI has a snackbar/toast component built in, so I would use that: https://mui.com/material-ui/react-snackbar (once https://github.com/sfbrigade/compass/pull/124 is merged)

Otherwise yes, sounds good!

**Comment by shin101** [comment]
Currently if a user hits an endpoint that does not exist (localhost:3000/hi for instance) they will be greeted with an error toast. Is this close to what we had in mind? I am happy to demo during the eng sync as well. 

![Image](https://github.com/sfbrigade/compass/assets/44033225/a1b61e5e-b6bb-4379-ac8f-a65631e8e7a9)

**Comment by codetheweb** [comment]
No, that might be useful but this issue was originally for displaying an error when a trpc mutation fails.

**Comment by shin101** [comment]
**Quick update** : 
Configured queryCache with an onError handler which gets triggered whenever an error occurs during a query or mutation. Seems to work correctly!

<img width="1452" alt="Screenshot 2023-07-04 at 10 16 52 AM" src="https://github.com/sfbrigade/compass/assets/44033225/65f829b9-a59a-458e-8cd8-47fb04e67335">

With existing mutations like creating a new para or a student for instance, currently we are console logging the error but would it make sense for me to change existing code in MyStudents.tsx and MyParas.tsx so that the toast is displayed instead?

**Comment by codetheweb** [comment]
awesome, yes I'd change/remove the current `onError` handlers

**Comment by shin101** [comment]
Update : will be refactoring this code quite a bit since there are new design requirements that the current toast library cannot handle
